### ISSUE TITLE
useObservableState throws error!

### ISSUE THREAD

**Issue by hansschenker** [benlesh/rxooks#2]

**Comment by hansschenker** [comment]
Uncaught TypeError: Cannot read properties of null (reading 'useRef')
    at useRef (react.development.js:1628:1)
    at useObservableState (index.js:31:28)
    at Search (search.tsx:19:61)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
